name : Build and deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: action/checkout@v2
      - name: say hello to my lover
      - run: echo " staff ija yayamba kutheka"
